### PR TITLE
Lernen.cloud Flavor

### PR DESCRIPTION
**Pull request by tobiasrohloff**
This PR provides the flavor for [lernen.cloud](lernen.cloud).

### CODE REVIEW

**Comment by tobiasrohloff** [comment]
I will probably clean up the assets and colors for all flavors in a future PR. It starts to get messy.

**Comment by tobiasrohloff** [comment]
Some visuals:

**Comment by bengelhaupt** [comment]
You could as well already add the Google Play link to the Readme

**Comment by tobiasrohloff** [comment]
>You could as well already add the Google Play link to the Readme

I plan to refresh the README in general soon.

**Pull request merged**
