### PR TITLE
Android 11

### PR DESCRIPTION
**Pull request by tobiasrohloff**
Update dependencies and migrate to Android 11.

### CODE REVIEW

**Comment by tobiasrohloff** [comment]
I outsourced the update of ExoPlayer into another [ticket](https://github.com/openHPI/xikolo-android/issues/275).

**Comment by tobiasrohloff** [comment]
@bengelhaupt @SanJSp please test with your devices and the emulator if everything works fine.

**Comment by bengelhaupt** [comment]
Is the change in the tab layout expected? I think it comes from the new `material:1.2.1` version. The production version has the tabs aligned left.

**Comment by tobiasrohloff** [comment]
@bengelhaupt good catch. The `tabGravity` was set to `center` all the time but somehow this was ignored. Weird. I changed it to `start`.

**Review by bengelhaupt — APPROVED** [review]

**Pull request merged**
